name: Build zip
on:
  release:
    types:
      - published

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        name: Set up PHP
        with:
          php-version: 8.2
          coverage: none

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@v2
        with:
          working-directory: plugin-dir
          composer-options: "--no-dev"

      - name: Remove all files and directories except plugin directory
        run: |
          find . -mindepth 1 -maxdepth 1 -not -name 'plugin-dir' -exec rm -rf {} +

      # Rename plugin directory to the plugin name
      - run: mv plugin-dir safety-passwords

      # Zip the plugin directory
      - name: Zip the plugin directory
        run: zip -r safety-passwords-wp-plugin.zip safety-passwords

      - name: Upload Release Artifact
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ./safety-passwords-wp-plugin.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
